export const customSelectStyles = {
  control: (provided, state) => ({
    ...provided,
    display: "flex",
    alignItems: "center",
    backgroundColor: "#f1efeb",
    borderRadius: "100px",
    border: "1px solid #000",
    height: 35,
    padding: "5px",
    boxShadow: "none",
    width: "140px",
    "&:hover": {
      borderColor: "#000",
    },
    borderColor: state.isFocused ? "#000" : "#000",
  }),
  option: (provided, state) => ({
    ...provided,
    backgroundColor: state.isSelected ? "#000" : "#f1efeb",
    color: state.isSelected ? "#fff" : "#000",
    "&:hover": {
      backgroundColor: "#000",
      color: "#fff",
    },
    padding: 10,
    fontSize: 16,
  }),
  singleValue: (provided) => ({
    ...provided,
    color: "#000",
    fontSize: 16,
    margin: 0,
    position: "relative",
    bottom: 5,
  }),
  menu: (provided) => ({
    ...provided,
    backgroundColor: "#f1efeb",
    borderRadius: "10px",
    border: "1px solid #000",
    marginTop: 0,
    width: "140px",
    fontSize: 16,
  }),
  dropdownIndicator: (provided, state) => ({
    ...provided,
    position: "relative",
    bottom: 4,
    color: state.isFocused ? "#000" : "#000",
    "&:hover": {
      cursor: "pointer",
      color: "#000",
    },
  }),
  placeholder: (provided) => ({
    ...provided,
    position: "relative",
    bottom: 5,
    fontSize: 16,
  }),
  input: (provided) => ({
    ...provided,
    position: "relative",
    bottom: 5,
    fontSize: 16,
  }),
  indicatorSeparator: (provided) => ({
    ...provided,
    position: "relative",
    bottom: 5,
    backgroundColor: "#000",
  }),
};

export const customSelectStylesModelViewer = {
  control: (provided, state) => ({
    ...provided,
    display: "flex",
    alignItems: "center",
    backgroundColor: "#f1efeb",
    borderRadius: "100px",
    border: "1px solid #000",
    top: 10,
    position: "absolute",
    right: 10,
    height: 35,
    padding: "5px",
    boxShadow: "none",
    width: "130px",
    "&:hover": {
      borderColor: "#000",
    },
    borderColor: state.isFocused ? "#000" : "#000",
  }),
  option: (provided, state) => ({
    ...provided,
    backgroundColor: state.isSelected ? "#000" : "#f1efeb",
    color: state.isSelected ? "#fff" : "#000",
    "&:hover": {
      backgroundColor: "#000",
      color: "#fff",
    },
    padding: 10,
  }),
  singleValue: (provided) => ({
    ...provided,
    color: "#000",
    fontSize: 16,
    margin: 0,
    position: "relative",
    bottom: 5,
  }),
  menu: (provided) => ({
    ...provided,
    backgroundColor: "#f1efeb",
    borderRadius: "10px",
    border: "1px solid #000",
    marginTop: "48px",
    width: "130px",
    position: "absolute",
    right: 10,
  }),
  dropdownIndicator: (provided, state) => ({
    ...provided,
    color: state.isFocused ? "#000" : "#000",
    position: "relative",
    bottom: 4,
    "&:hover": {
      color: "#000",
    },
  }),
  placeholder: (provided) => ({
    ...provided,
    position: "relative",
    bottom: 5,
  }),
  input: (provided) => ({
    ...provided,
    position: "relative",
    bottom: 5,
  }),
  indicatorSeparator: (provided) => ({
    ...provided,
    position: "relative",
    bottom: 5,
    backgroundColor: "#000",
  }),
};
